language: node_js

node_js:
  - "iojs"
  - "0.12"
  - "0.10"

notifications:
  irc:
    use_notice: true
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#graphql"
  slack:
    secure: G7fzaXoPI1cyyW7dlpQ8oG/ot73n4kE83HgbyK1iEN1YBfodsytVgh0jS+zB3DhhRAotS/VfGVz9Wj2Oo109U5w/FyxdMGuKvFan/0B/aAws1sPxLGWA5230u1wTKQCHAu17+yppFOODUu1ILDXaD2A//Wj5iru9M4NnKc1bO6VHkfBHPTLQLbdPHmorwuSH02Ocbh7K4XOWzXRxM6VrwamEn1KnyXGu2w3QdJUT31OjGEEdf6FUzvjwzFgXPhngCw5+enpwm71ljHDNu8YHhXvHtS4328O5pYQO8np7j653HNEqi+ZUiYEOWpwC8be1xHdvi/s32tPFZiCx28ZmDoCUrY744tpPtE6tzuncmSKB0Y3EjutdXBpxllNr5l5hpX5092G2MlpokFbv85J+E2ALcZYNYeFOqTYTKwTYkxK6B1x4amBNpM+FXgUhloK4BK9OT0Qh5SiQOsM8cZT0h6QP91n+REljtpugW3VbuIxq5OJAi42FYbHBC27pohhq6ohU1euZfobk9a7ZawnjoEUk1EZHXiJzYKY/QqzyB6dwk0ersBl3l3OX/wnjwKTkqc9aTmDWo2L+lHaUCXuCY1+KQXsRicfnH395szTJXQbvcbN0zz188gdz6sawzi5BxndWo0NRwZyOG2YcyUHFQR4bK1rL7Lo6t6rijQ/XMeQ=

deploy:
  provider: npm
  email: "lee@leebyron.com"
  api_key:
    secure: NefvASrtqfXoqcfQGgnsLb6mNdW+G0n2XebrmYd7tn4rpkYUQ2esuAOPj7ULBZ0VWUxEuvMB/OB6xHvGaTmYilsT80/+3PSp2LyvbHCxWSjcxweTqrcCi2ZIuOWvZ6L+XA0FpY5BVn6SLUgy++H4s+qfvVX7d9cV5ayQPCZOCheQ/HFatJ65m27o7Bxx3LDI/hZvbbYIReab4hOmzJ6Ci5Yzaw00aRNLaGu2Tsf7Vz0MjhIZ1U1+CE9Mj2/JGiEslBM4PnVA8JLp+suK0d7OPqtxBOJBe+DTjO6U2d3G5tD5eEjAz4wyLjkc2hWlEV4Nb8p/dhyZ88LrWgfXjT1S4bUF3VGJX2S7bnkhUrxg48M5bA5mJoNhJdg53xxjm5LeG6tEtzYcItVVjb19rWhBgb3wIkgNciVJEQaN+EVaGSLVoDUq+4GgqLzmbsuEsHEiVePeegQYvhgLYto5nn03UWRb46qH6dwF8Mtkv7eucxL/tw1LJI1Bz0UqakEFf3BHWJMrYkfMbikP3Bxp2N2QrieOkTKPi+suKOILpoOERt+eGJR4hsAg1R2isChYbMKoZy16aUVEqTklA3u2AeT54RAPXTbuYcvXZ3AHb9ACzEtRTYz5a6vQkkJHxemWxhJtF3HqLPE6nVM167B59swA09vWCQKSlXNDKBawV9R7O0E=
  on:
    tags: true
    branch: master

after_success:
  - npm run coveralls
