language: node_js

node_js:
  - "iojs"
  - "0.12"
  - "0.10"

notifications:
  irc:
    use_notice: true
    on_success: change
    on_failure: change
    channels:
      - chat.freenode.net#graphql

after_success:
  - npm run coveralls
